contacts/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'contacts.views',
    url(r'^companies/page/(?P<page>\d+)/$', view='company.list',
        name='contacts_company_list_paginated'),
    url(r'^companies/add/$', view='company.create',
        name='contacts_company_create'),
    url(r'^companies/(?P<pk>\d+)-(?P<slug>[-\w]+)/delete/$',
        view='company.delete', name='contacts_company_delete'),
    url(r'^companies/(?P<pk>\d+)/delete/$', view='company.delete',
        name='contacts_company_delete'),
    url(r'^companies/(?P<pk>\d+)-(?P<slug>[-\w]+)/edit/$',
        view='company.update', name='contacts_company_update'),
    url(r'^companies/(?P<pk>\d+)/edit/$', view='company.update',
        name='contacts_company_update'),
    url(r'^companies/(?P<pk>\d+)-(?P<slug>[-\w]+)/$',
        view='company.detail', name='contacts_company_detail'),
    url(r'^companies/(?P<pk>\d+)/$', view='company.detail',
        name='contacts_company_detail'),
    url(r'^companies/$', view='company.list', name='contacts_company_list'),

    url(r'^people/page/(?P<page>\d+)/$', view='person.list',
        name='contacts_person_list_paginated'),
    url(r'^people/add/$', view='person.create', name='contacts_person_create'),
    url(r'^people/(?P<pk>\d+)-(?P<slug>[-\w]+)/delete/$', view='person.delete',
        name='contacts_person_delete'),
    url(r'^people/(?P<pk>\d+)/delete/$', view='person.delete',
        name='contacts_person_delete'),
    url(r'^people/(?P<pk>\d+)-(?P<slug>[-\w]+)/edit/$', view='person.update',
        name='contacts_person_update'),
    url(r'^people/(?P<pk>\d+)/edit/$', view='person.update',
        name='contacts_person_update'),
    url(r'^people/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', view='person.detail',
        name='contacts_person_detail'),
    url(r'^people/(?P<pk>\d+)/$', view='person.detail',
        name='contacts_person_detail'),
    url(r'^people/$', view='person.list', name='contacts_person_list'),

    url(r'^groups/page/(?P<page>\d+)/$', view='group.list',
        name='contacts_group_list_paginated'),
    url(r'^groups/add/$', view='group.create',
        name='contacts_group_create'),
    url(r'^groups/(?P<pk>\d+)-(?P<slug>[-\w]+)/delete/$', view='group.delete',
        name='contacts_group_delete'),
    url(r'^groups/(?P<pk>\d+)/delete/$', view='group.delete',
        name='contacts_group_delete'),
    url(r'^groups/(?P<pk>\d+)-(?P<slug>[-\w]+)/edit/$', view='group.update',
        name='contacts_group_update'),
    url(r'^groups/(?P<pk>\d+)/edit/$', view='group.update',
        name='contacts_group_update'),
    url(r'^groups/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', view='group.detail',
        name='contacts_group_detail'),
    url(r'^groups/(?P<pk>\d+)/$', view='group.detail',
        name='contacts_group_detail'),
    url(r'^groups/$', view='group.list', name='contacts_group_list'),
)

contacts/models.py
from django.db import models
from django.db.models import permalink
from django.conf import settings
from django.utils.translation import ugettext as _
from django.utils.encoding import python_2_unicode_compatible
from django_comments.models import Comment
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import (GenericRelation,
                                                GenericForeignKey)

from contacts.managers import SpecialDateManager


@python_2_unicode_compatible
class Company(models.Model):
    """Company model."""
    name = models.CharField(_('name'), max_length=200)
    nickname = models.CharField(_('nickname'), max_length=50, blank=True,
                                null=True)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)
    about = models.TextField(_('about'), blank=True, null=True)
    logo = models.ImageField(_('photo'), upload_to='contacts/companies/',
                             blank=True)

    phone_number = GenericRelation('PhoneNumber')
    email_address = GenericRelation('EmailAddress')
    instant_messenger = GenericRelation('InstantMessenger')
    web_site = GenericRelation('WebSite')
    street_address = GenericRelation('StreetAddress')
    special_date = GenericRelation('SpecialDate')
    note = GenericRelation(Comment, object_id_field='object_pk')

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    class Meta:
        db_table = 'contacts_companies'
        ordering = ('name',)
        verbose_name = _('company')
        verbose_name_plural = _('companies')

    def __str__(self):
        return "%s" % self.name

    @permalink
    def get_absolute_url(self):
        return ('contacts_company_detail', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_update_url(self):
        return ('contacts_company_update', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_delete_url(self):
        return ('contacts_company_delete', None, {
            'pk': self.pk,
            'slug': self.slug,
        })


@python_2_unicode_compatible
class Person(models.Model):
    """Person model."""
    first_name = models.CharField(_('first name'), max_length=100)
    last_name = models.CharField(_('last name'), max_length=200)
    middle_name = models.CharField(_('middle name'), max_length=200, blank=True, null=True)
    suffix = models.CharField(_('suffix'), max_length=50, blank=True, null=True)
    nickname = models.CharField(_('nickname'), max_length=100, blank=True)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)
    title = models.CharField(_('title'), max_length=200, blank=True)
    company = models.ForeignKey(Company, blank=True, null=True)
    about = models.TextField(_('about'), blank=True)
    photo = models.ImageField(_('photo'), upload_to='contacts/person/',
                              blank=True)

    user = models.OneToOneField(settings.AUTH_USER_MODEL, blank=True,
                                null=True, verbose_name=_('user'))

    phone_number = GenericRelation('PhoneNumber')
    email_address = GenericRelation('EmailAddress')
    instant_messenger = GenericRelation('InstantMessenger')
    web_site = GenericRelation('WebSite')
    street_address = GenericRelation('StreetAddress')
    special_date = GenericRelation('SpecialDate')
    note = GenericRelation(Comment, object_id_field='object_pk')

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    class Meta:
        db_table = 'contacts_people'
        ordering = ('last_name', 'first_name')
        verbose_name = _('person')
        verbose_name_plural = _('people')

    def __str__(self):
        return self.fullname

    @property
    def fullname(self):
        return "%s %s" % (self.first_name, self.last_name)

    @permalink
    def get_absolute_url(self):
        return ('contacts_person_detail', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_update_url(self):
        return ('contacts_person_update', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_delete_url(self):
        return ('contacts_person_delete', None, {
            'pk': self.pk,
            'slug': self.slug,
        })


@python_2_unicode_compatible
class Group(models.Model):
    """Group model."""
    name = models.CharField(_('name'), max_length=200)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)
    about = models.TextField(_('about'), blank=True)

    people = models.ManyToManyField(Person, verbose_name='people', blank=True)
    companies = models.ManyToManyField(Company, verbose_name='companies',
                                       blank=True)

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    class Meta:
        db_table = 'contacts_groups'
        ordering = ('name',)
        verbose_name = _('group')
        verbose_name_plural = _('groups')

    def __str__(self):
        return "%s" % self.name

    @permalink
    def get_absolute_url(self):
        return ('contacts_group_detail', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_update_url(self):
        return ('contacts_group_update', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_delete_url(self):
        return ('contacts_group_delete', None, {
            'pk': self.pk,
            'slug': self.slug,
        })


@python_2_unicode_compatible
class Location(models.Model):
    """Location model."""
    WEIGHT_CHOICES = [(i, i) for i in range(11)]

    name = models.CharField(_('name'), max_length=200)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)

    is_phone = models.BooleanField(_('is phone'), default=False,
        help_text=_("Only used for Phone"))
    is_street_address = models.BooleanField(_('is street address'),
        default=False, help_text=_("Only used for Street Address"))

    weight = models.IntegerField(choices=WEIGHT_CHOICES, default=0)

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    def __str__(self):
        return "%s" % (self.name)

    class Meta:
        db_table = 'contacts_locations'
        ordering = ('weight',)
        verbose_name = _('location')
        verbose_name_plural = _('locations')


@python_2_unicode_compatible
class PhoneNumber(models.Model):
    """Phone Number model."""
    content_type = models.ForeignKey(ContentType, limit_choices_to={
        'app_label': 'contacts'})
    object_id = models.IntegerField(db_index=True)
    content_object = GenericForeignKey()

    phone_number = models.CharField(_('number'), max_length=50)
    location = models.ForeignKey(Location, limit_choices_to={
        'is_street_address': False})

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    def __str__(self):
        return "%s (%s)" % (self.phone_number, self.location)

    class Meta:
        db_table = 'contacts_phone_numbers'
        verbose_name = _('phone number')
        verbose_name_plural = _('phone numbers')


@python_2_unicode_compatible
class EmailAddress(models.Model):
    content_type = models.ForeignKey(ContentType, limit_choices_to={
        'app_label': 'contacts'})
    object_id = models.IntegerField(db_index=True)
    content_object = GenericForeignKey()

    email_address = models.EmailField(_('email address'))
    location = models.ForeignKey(Location, limit_choices_to={
        'is_street_address': False, 'is_phone': False})

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    def __str__(self):
        return "%s (%s)" % (self.email_address, self.location)

    class Meta:
        db_table = 'contacts_email_addresses'
        verbose_name = _('email address')
        verbose_name_plural = _('email addresses')


@python_2_unicode_compatible
class InstantMessenger(models.Model):
    OTHER = 'other'

    IM_SERVICE_CHOICES = (
        ('aim', _('AIM')),
        ('msn', _('MSN')),
        ('icq', _('ICQ')),
        ('jabber', _('Jabber')),
        ('yahoo', _('Yahoo')),
        ('skype', _('Skype')),
        ('qq', _('QQ')),
        ('sametime', _('Sametime')),
        ('gadu-gadu', _('Gadu-Gadu')),
        ('google-talk', _('Google Talk')),
        (OTHER, _('Other'))
    )

    content_type = models.ForeignKey(ContentType, limit_choices_to={
        'app_label': 'contacts'})
    object_id = models.IntegerField(db_index=True)
    content_object = GenericForeignKey()

    im_account = models.CharField(_('im account'), max_length=100)
    location = models.ForeignKey(Location, limit_choices_to={
        'is_street_address': False, 'is_phone': False})
    service = models.CharField(_('service'), max_length=11,
                               choices=IM_SERVICE_CHOICES, default=OTHER)

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    def __str__(self):
        return "%s (%s)" % (self.im_account, self.location)

    class Meta:
        db_table = 'contacts_instant_messengers'
        verbose_name = _('instant messenger')
        verbose_name_plural = _('instant messengers')


@python_2_unicode_compatible
class WebSite(models.Model):

contacts/templates/contacts/company/base.html
{% extends "contacts/base.html" %}

contacts/templates/contacts/company/create.html
{% extends "contacts/company/base.html" %}
{% load i18n %}

{% block title %}{{ block.super }}: {% trans "Create a new Company" %}{% endblock %}

{% block content_title %}
	<h2>{% trans "Create a new Company" %}</h2>
{% endblock %}

{% block content %}
	<form action="." method="post" accept-charset="utf-8">
        {% csrf_token %}
		{{ form.as_p }}

		{% for form in phone_formset.forms %}
			{{ form.as_p }}
		{% endfor %}

		<p><input type="submit" value="{% trans "Create" %}"></p>
	</form>
{% endblock %}

contacts/templates/contacts/company/delete.html
{% extends "contacts/company/base.html" %}
{% load i18n %}

{% block title %}{{ block.super }}: {% trans "Delete" %} {{ object.name }}{% endblock %}

{% block content_title %}
	<h2>{% trans "Delete" %} {{ object.name }}</h2>
{% endblock %}

{% block content %}
	<form action="." method="post" accept-charset="utf-8">
        {% csrf_token %}
		<p>
			<select name="delete_company" id="delete_company" size="1">
				<option value="No">{% trans "No" %}</option>
				<option value="Yes">{% trans "Yes" %}</option>
			</select>
			<input type="submit" value="{% trans "Submit" %}">
		</p>
	</form>
{% endblock %}

contacts/templates/contacts/company/detail.html
{% extends "contacts/company/base.html" %}
{% load i18n %}

{% block title %}{{ block.super }}: {{ object }}{% endblock %}

{% block content_title %}
	<h2>
		<span class="fn">{{ object }}</span>
		{% if object.nickname %}
		<span class="alt">(<span class="nickname">{{ object.nickname }}</span>)</span>
		{% endif %}
	</h2>
{% endblock %}

{% block content %}
	<p>
		<a href="{{ object.get_update_url }}">{% trans "Update" %}</a>
		<a href="{{ object.get_delete_url }}">{% trans "Delete" %}</a>
	</p>
	
	{{ object.about|linebreaks }}
	
	{% if object.person_set.all %}
		<h3>People</h3>

		<ul class="link_list">
		{% for person in object.person_set.all %}
			<li>
				<a href="{{ person.get_absolute_url }}">{{ person }}</a>
				{% if person.title %}
					<span class="alt">({{ person.title }})</span>
				{% endif %}
			</li>
		{% endfor %}
		</ul>
	{% endif %}
	
	{% include "contacts/_phone_number_list.html" %}
	{% include "contacts/_email_address_list.html" %}
	{% include "contacts/_instant_messenger_list.html" %}
	{% include "contacts/_street_address_list.html" %}
	{% include "contacts/_web_site_list.html" %}
	{% include "contacts/_special_date_list.html" %}
	{% include "contacts/_comment_list.html" %}
{% endblock %}

contacts/templates/contacts/company/list.html
{% extends "contacts/company/base.html" %}
{% load i18n %}

{% block title %}{{ block.super }}: {% trans "Companies" %}{% endblock %}

{% block content_title %}
	<h2>{% trans "Companies" %}</h2>
{% endblock %}

{% block content %}
	<p>
		<a href="{% url "contacts_company_create" %}">{% trans "Create" %}</a>
	</p>

	<ul class="link_list">
	{% for company in object_list %}
		<li id="company-{{ company.id }}"><a href="{{ company.get_absolute_url }}">{{ company }}</a></li>
	{% endfor %}
	</ul>
{% endblock %}

contacts/templates/contacts/company/update.html
{% extends "contacts/company/base.html" %}
{% load i18n %}

{% block title %}{{ block.super }}: Edit {{ object.name }}{% endblock %}

{% block content_title %}
	<h2>{% trans "Edit" %} {{ object.name }}</h2>
{% endblock %}

{% block content %}
	<form action="." method="post" accept-charset="utf-8">
        {% csrf_token %}
		<p>{{ form.name }}</p>

		{% include "contacts/_phone_number_form.html" %}
		{% include "contacts/_email_address_form.html" %}
		{% include "contacts/_instant_messenger_form.html" %}
		{% include "contacts/_web_site_form.html" %}
		{% include "contacts/_street_address_form.html" %}
		{% include "contacts/_special_date_form.html" %}

		<p><input type="submit" value="{% trans "Save" %}"></p>
	</form>
{% endblock %}