contacts/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'contacts.views',
    url(r'^companies/page/(?P<page>\d+)/$', view='company.list',
        name='contacts_company_list_paginated'),
    url(r'^companies/add/$', view='company.create',
        name='contacts_company_create'),
    url(r'^companies/(?P<pk>\d+)-(?P<slug>[-\w]+)/delete/$',
        view='company.delete', name='contacts_company_delete'),
    url(r'^companies/(?P<pk>\d+)/delete/$', view='company.delete',
        name='contacts_company_delete'),
    url(r'^companies/(?P<pk>\d+)-(?P<slug>[-\w]+)/edit/$',
        view='company.update', name='contacts_company_update'),
    url(r'^companies/(?P<pk>\d+)/edit/$', view='company.update',
        name='contacts_company_update'),
    url(r'^companies/(?P<pk>\d+)-(?P<slug>[-\w]+)/$',
        view='company.detail', name='contacts_company_detail'),
    url(r'^companies/(?P<pk>\d+)/$', view='company.detail',
        name='contacts_company_detail'),
    url(r'^companies/$', view='company.list', name='contacts_company_list'),

    url(r'^people/page/(?P<page>\d+)/$', view='person.list',
        name='contacts_person_list_paginated'),
    url(r'^people/add/$', view='person.create', name='contacts_person_create'),
    url(r'^people/(?P<pk>\d+)-(?P<slug>[-\w]+)/delete/$', view='person.delete',
        name='contacts_person_delete'),
    url(r'^people/(?P<pk>\d+)/delete/$', view='person.delete',
        name='contacts_person_delete'),
    url(r'^people/(?P<pk>\d+)-(?P<slug>[-\w]+)/edit/$', view='person.update',
        name='contacts_person_update'),
    url(r'^people/(?P<pk>\d+)/edit/$', view='person.update',
        name='contacts_person_update'),
    url(r'^people/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', view='person.detail',
        name='contacts_person_detail'),
    url(r'^people/(?P<pk>\d+)/$', view='person.detail',
        name='contacts_person_detail'),
    url(r'^people/$', view='person.list', name='contacts_person_list'),

    url(r'^groups/page/(?P<page>\d+)/$', view='group.list',
        name='contacts_group_list_paginated'),
    url(r'^groups/add/$', view='group.create',
        name='contacts_group_create'),
    url(r'^groups/(?P<pk>\d+)-(?P<slug>[-\w]+)/delete/$', view='group.delete',
        name='contacts_group_delete'),
    url(r'^groups/(?P<pk>\d+)/delete/$', view='group.delete',
        name='contacts_group_delete'),
    url(r'^groups/(?P<pk>\d+)-(?P<slug>[-\w]+)/edit/$', view='group.update',
        name='contacts_group_update'),
    url(r'^groups/(?P<pk>\d+)/edit/$', view='group.update',
        name='contacts_group_update'),
    url(r'^groups/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', view='group.detail',
        name='contacts_group_detail'),
    url(r'^groups/(?P<pk>\d+)/$', view='group.detail',
        name='contacts_group_detail'),
    url(r'^groups/$', view='group.list', name='contacts_group_list'),
)

contacts/models.py
from django.db import models
from django.db.models import permalink
from django.conf import settings
from django.utils.translation import ugettext as _
from django.utils.encoding import python_2_unicode_compatible
from django_comments.models import Comment
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import (GenericRelation,
                                                GenericForeignKey)

from contacts.managers import SpecialDateManager


@python_2_unicode_compatible
class Company(models.Model):
    """Company model."""
    name = models.CharField(_('name'), max_length=200)
    nickname = models.CharField(_('nickname'), max_length=50, blank=True,
                                null=True)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)
    about = models.TextField(_('about'), blank=True, null=True)
    logo = models.ImageField(_('photo'), upload_to='contacts/companies/',
                             blank=True)

    phone_number = GenericRelation('PhoneNumber')
    email_address = GenericRelation('EmailAddress')
    instant_messenger = GenericRelation('InstantMessenger')
    web_site = GenericRelation('WebSite')
    street_address = GenericRelation('StreetAddress')
    special_date = GenericRelation('SpecialDate')
    note = GenericRelation(Comment, object_id_field='object_pk')

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    class Meta:
        db_table = 'contacts_companies'
        ordering = ('name',)
        verbose_name = _('company')
        verbose_name_plural = _('companies')

    def __str__(self):
        return "%s" % self.name

    @permalink
    def get_absolute_url(self):
        return ('contacts_company_detail', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_update_url(self):
        return ('contacts_company_update', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_delete_url(self):
        return ('contacts_company_delete', None, {
            'pk': self.pk,
            'slug': self.slug,
        })


@python_2_unicode_compatible
class Person(models.Model):
    """Person model."""
    first_name = models.CharField(_('first name'), max_length=100)
    last_name = models.CharField(_('last name'), max_length=200)
    middle_name = models.CharField(_('middle name'), max_length=200, blank=True, null=True)
    suffix = models.CharField(_('suffix'), max_length=50, blank=True, null=True)
    nickname = models.CharField(_('nickname'), max_length=100, blank=True)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)
    title = models.CharField(_('title'), max_length=200, blank=True)
    company = models.ForeignKey(Company, blank=True, null=True)
    about = models.TextField(_('about'), blank=True)
    photo = models.ImageField(_('photo'), upload_to='contacts/person/',
                              blank=True)

    user = models.OneToOneField(settings.AUTH_USER_MODEL, blank=True,
                                null=True, verbose_name=_('user'))

    phone_number = GenericRelation('PhoneNumber')
    email_address = GenericRelation('EmailAddress')
    instant_messenger = GenericRelation('InstantMessenger')
    web_site = GenericRelation('WebSite')
    street_address = GenericRelation('StreetAddress')
    special_date = GenericRelation('SpecialDate')
    note = GenericRelation(Comment, object_id_field='object_pk')

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    class Meta:
        db_table = 'contacts_people'
        ordering = ('last_name', 'first_name')
        verbose_name = _('person')
        verbose_name_plural = _('people')

    def __str__(self):
        return self.fullname

    @property
    def fullname(self):
        return "%s %s" % (self.first_name, self.last_name)

    @permalink
    def get_absolute_url(self):
        return ('contacts_person_detail', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_update_url(self):
        return ('contacts_person_update', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_delete_url(self):
        return ('contacts_person_delete', None, {
            'pk': self.pk,
            'slug': self.slug,
        })


@python_2_unicode_compatible
class Group(models.Model):
    """Group model."""
    name = models.CharField(_('name'), max_length=200)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)
    about = models.TextField(_('about'), blank=True)

    people = models.ManyToManyField(Person, verbose_name='people', blank=True)
    companies = models.ManyToManyField(Company, verbose_name='companies',
                                       blank=True)

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    class Meta:
        db_table = 'contacts_groups'
        ordering = ('name',)
        verbose_name = _('group')
        verbose_name_plural = _('groups')

    def __str__(self):
        return "%s" % self.name

    @permalink
    def get_absolute_url(self):
        return ('contacts_group_detail', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_update_url(self):
        return ('contacts_group_update', None, {
            'pk': self.pk,
            'slug': self.slug,
        })

    @permalink
    def get_delete_url(self):
        return ('contacts_group_delete', None, {
            'pk': self.pk,
            'slug': self.slug,
        })


@python_2_unicode_compatible
class Location(models.Model):
    """Location model."""
    WEIGHT_CHOICES = [(i, i) for i in range(11)]

    name = models.CharField(_('name'), max_length=200)
    slug = models.SlugField(_('slug'), max_length=50, unique=True)

    is_phone = models.BooleanField(_('is phone'), default=False,
        help_text=_("Only used for Phone"))
    is_street_address = models.BooleanField(_('is street address'),
        default=False, help_text=_("Only used for Street Address"))

    weight = models.IntegerField(choices=WEIGHT_CHOICES, default=0)

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    def __str__(self):
        return "%s" % (self.name)

    class Meta:
        db_table = 'contacts_locations'
        ordering = ('weight',)
        verbose_name = _('location')
        verbose_name_plural = _('locations')


@python_2_unicode_compatible
class PhoneNumber(models.Model):
    """Phone Number model."""
    content_type = models.ForeignKey(ContentType, limit_choices_to={
        'app_label': 'contacts'})
    object_id = models.IntegerField(db_index=True)
    content_object = GenericForeignKey()

    phone_number = models.CharField(_('number'), max_length=50)
    location = models.ForeignKey(Location, limit_choices_to={
        'is_street_address': False})

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    def __str__(self):
        return "%s (%s)" % (self.phone_number, self.location)

    class Meta:
        db_table = 'contacts_phone_numbers'
        verbose_name = _('phone number')
        verbose_name_plural = _('phone numbers')


@python_2_unicode_compatible
class EmailAddress(models.Model):
    content_type = models.ForeignKey(ContentType, limit_choices_to={
        'app_label': 'contacts'})
    object_id = models.IntegerField(db_index=True)
    content_object = GenericForeignKey()

    email_address = models.EmailField(_('email address'))
    location = models.ForeignKey(Location, limit_choices_to={
        'is_street_address': False, 'is_phone': False})

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    def __str__(self):
        return "%s (%s)" % (self.email_address, self.location)

    class Meta:
        db_table = 'contacts_email_addresses'
        verbose_name = _('email address')
        verbose_name_plural = _('email addresses')


@python_2_unicode_compatible
class InstantMessenger(models.Model):
    OTHER = 'other'

    IM_SERVICE_CHOICES = (
        ('aim', _('AIM')),
        ('msn', _('MSN')),
        ('icq', _('ICQ')),
        ('jabber', _('Jabber')),
        ('yahoo', _('Yahoo')),
        ('skype', _('Skype')),
        ('qq', _('QQ')),
        ('sametime', _('Sametime')),
        ('gadu-gadu', _('Gadu-Gadu')),
        ('google-talk', _('Google Talk')),
        (OTHER, _('Other'))
    )

    content_type = models.ForeignKey(ContentType, limit_choices_to={
        'app_label': 'contacts'})
    object_id = models.IntegerField(db_index=True)
    content_object = GenericForeignKey()

    im_account = models.CharField(_('im account'), max_length=100)
    location = models.ForeignKey(Location, limit_choices_to={
        'is_street_address': False, 'is_phone': False})
    service = models.CharField(_('service'), max_length=11,
                               choices=IM_SERVICE_CHOICES, default=OTHER)

    date_added = models.DateTimeField(_('date added'), auto_now_add=True)
    date_modified = models.DateTimeField(_('date modified'), auto_now=True)

    def __str__(self):
        return "%s (%s)" % (self.im_account, self.location)

    class Meta:
        db_table = 'contacts_instant_messengers'
        verbose_name = _('instant messenger')
        verbose_name_plural = _('instant messengers')


@python_2_unicode_compatible
class WebSite(models.Model):

contacts/templates/contacts/_comment_list.html
{% load i18n comments %}
{% get_comment_form for object as form %}

<div id="contact_notes">
	<form action="{% url "comments-post-comment" %}" method="post" accept-charset="utf-8">
		<p><label for="id_comment">{% trans "Comment" %}</label><textarea name="comment" id="id_comment" rows="8" cols="40"></textarea></p>
		<p><input type="submit" value="{% trans "Add" %}"></p>
		{% csrf_token %}{{ form.security_hash }}{{ form.timestamp }}{{ form.content_type }}{{ form.object_pk }}
		<input type="hidden" name="next" value="{{ object.get_absolute_url }}">
	</form>

	{% if object.note.all %}
	<h3>{% trans "Notes" %}</h3>

	{% for note in object.note.all %}
	<div id="note-{{ note.id }}">
		<h4>
			{{ note.submit_date }}
			<span class="alt">
				{% if user.name %}
				({{ note.user.name }})
				{% else %}
				({{ note.user.username }})
				{% endif %}
			</span>
			<a href="#note-{{ note.id }}">#</a>
		</h4>
		
		{{ note.comment|linebreaks }}
		{% endfor %}
	</div>
	{% endif %}
</div>

contacts/templates/contacts/_email_address_form.html
{% load i18n %}

<fieldset id="email_addresses" class="">
	<legend>{% trans "Email addresses" %}</legend>
	{{ email_formset.management_form }}
	{% for form in email_formset.forms %}
	<p>
		{{ form.email_address }}
		{{ form.location }}
		<label>{{ form.DELETE.label }}</label>
		{{ form.DELETE }}
		{{ form.id }}
	</p>
	{% endfor %}
</fieldset>

contacts/templates/contacts/_email_address_list.html
{% load i18n %}

{% if object.email_address.all %}
<div id="contant_emails">
	<h3>{% trans "Email Addresses" %}</h3>
	
	<ul class="link_list">
	{% for email in object.email_address.all %}
		<li class="email">
			<a href="mailto:{{ email.email_address }}" class="value">{{ email.email_address }}</a>
			<span class="alt">(<span class="type">{{ email.get_location_display }}</span>)</span>
		</li>
	{% endfor %}
	</ul>
	
</div>
{% endif %}

contacts/templates/contacts/_instant_messenger_form.html
{% load i18n %}

<fieldset id="instant_messengers">
	<legend>{% trans "Instant messengers" %}</legend>
	{{ im_formset.management_form }}
	{% for form in im_formset.forms %}
	<p>
		{{ form.im_account }}
		{{ form.service }}
		{{ form.location }}
		<label>{{ form.DELETE.label }}</label>
		{{ form.DELETE }}
		{{ form.id }}
	</p>
	{% endfor %}
</fieldset>

contacts/templates/contacts/_instant_messenger_list.html
{% load i18n %}

{% if object.instant_messenger.all %}
<div id="contant_ims">
	<h3>{% trans "Instant Messengers" %}</h3>
	
	<ul class="link_list">
	{% for im in object.instant_messenger.all %}
		<li>
			{{ im.im_account }}
			<span class="alt">({{ im.get_service_display }} @ {{ im.get_location_display }})</span>
		</li>
	{% endfor %}
	</ul>
</div>
{% endif %}

contacts/templates/contacts/_phone_number_form.html
{% load i18n %}

<fieldset id="phone_numbers">
	<legend>{% trans "Phone numbers" %}</legend>
	{{ phone_formset.management_form }}
	{% for form in phone_formset.forms %}
	<p>
		{{ form.phone_number }}
		{{ form.location }}
		<label>{{ form.DELETE.label }}</label>
		{{ form.DELETE }}
		{{ form.id }}
	</p>
	{% endfor %}
</fieldset>

contacts/templates/contacts/_phone_number_list.html
{% load i18n %}

{% if object.phone_number.all %}
<div id="contant_numbers">
	<h3>{% trans "Phone Numbers" %}</h3>
	
	<ul class="link_list">
	{% for phone in object.phone_number.all %}
		<li class="tel">
			<span class="value">{{ phone.phone_number }}</span>
			<span class="alt">(<span class="type">{{ phone.get_location_display }}</span>)</span>
		</li>
	{% endfor %}
	</ul>
</div>
{% endif %}

contacts/templates/contacts/_special_date_form.html
{% load i18n %}

<fieldset id="special_dates" class="">
	<legend>{% trans "Special Dates" %}</legend>
	{{ special_date_formset.management_form }}
	{% for form in special_date_formset.forms %}
	<p>
		{{ form.occasion }}
		{{ form.date }}
		<label>{{ form.every_year.label }}</label>{{ form.every_year }}
	</p>
	<p>
		<label>{{ form.DELETE.label }}</label>
		{{ form.DELETE }}
		{{ form.id }}
	</p>
	{% endfor %}
</fieldset>

contacts/templates/contacts/_special_date_list.html
{% load i18n %}

{% if object.special_date.all %}
<div id="contacts_special_dates">
	<h3>{% trans "Special dates" %}</h3>

	<ul class="link_list">
	{% for special_date in object.special_date.all %}
		<li>
		    <strong>{{ special_date.occasion }}</strong>:
		    {{ special_date.date|date:"jS F" }}{% if not special_date.every_year %}{{ special_date.date|date:"Y" }}{% endif %}
		</li>
	{% endfor %}
	</ul>
</div>
{% endif %}

contacts/templates/contacts/_street_address_form.html
{% load i18n %}

<fieldset id="street_addresses" class="">
	<legend>{% trans "Street addresses" %}</legend>
	{{ address_formset.management_form }}
	{% for form in address_formset.forms %}
	<p>
		<label>{{ form.street.label }}</label>{{ form.street }} {{ form.location }}<br>
		<label>{{ form.city.label }}</label>{{ form.city }}<br>
		<label>{{ form.province.label }}</label>{{ form.province }} <label>{{ form.postal_code.label }}</label>{{ form.postal_code }}<br>
		<label>{{ form.country.label }}</label>{{ form.country }}
		<label>{{ form.DELETE.label }}</label>
		{{ form.DELETE }}
		{{ form.id }}
	</p>
	{% endfor %}
</fieldset>

contacts/templates/contacts/_street_address_list.html
{% load i18n %}

{% if object.street_address.all %}
<div id="contant_addresses">
	<h3>{% trans "Street Addresses" %}</h3>
	
	<ul class="link_list">
	{% for address in object.street_address.all %}
		<li class="adr">
			<span class="street-address">{{ address.street }}</span><br>
			<span class="locality">{{ address.city }}</span>, <span class="region">{{ address.province }}</span><br>
			<span class="postal-code">{{ address.postal_code }}</span> <span class="country-name">{{ address.country }}</span>
			<span class="alt">(<span class="type">{{ address.get_location_display }}</span>)</span>
		</li>
	{% endfor %}
	</ul>
</div>
{% endif %}

contacts/templates/contacts/_web_site_form.html
{% load i18n %}

<fieldset id="web_sites">
	<legend>{% trans "Web sites" %}</legend>
	{{ website_formset.management_form }}
	{% for form in website_formset.forms %}
	<p>
		{{ form.url }}
		{{ form.location }}
		<label>{{ form.DELETE.label }}</label>
		{{ form.DELETE }}
		{{ form.id }}
	</p>
	{% endfor %}
</fieldset>

contacts/templates/contacts/_web_site_list.html
{% load i18n %}

{% if object.web_site.all %}
<div id="contacts_web_sites">
	<h3>{% trans "Web sites" %}</h3>

	<ul class="link_list">
	{% for web in object.web_site.all %}
		<li>
			<a href="{{ web.url }}" class="url">{{ web.url }}</a>
			<span class="alt">({{ web.get_location_display }})</span>
		</li>
	{% endfor %}
	</ul>
</div>
{% endif %}

contacts/templates/contacts/base.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Contacts" %}{% endblock %}

{% block body %}
	<div class="vcard">
		{% block content_title %}{% endblock %}
		{% block content %}{% endblock %}
	</div>
{% endblock %}